python -O search.py 114 experimenten/params_$1.txt
python -O search.py 118 experimenten/params_$1.txt
python -O search.py 122 experimenten/params_$1.txt
python -O search.py 126 experimenten/params_$1.txt
python -O search.py 130 experimenten/params_$1.txt
python -O search.py 134 experimenten/params_$1.txt
python -O search.py 138 experimenten/params_$1.txt
python -O search.py 142 experimenten/params_$1.txt
python -O search.py 146 experimenten/params_$1.txt
