/c/Users/Maarten/Miniconda3/python search.py 103 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 107 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 111 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 115 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 119 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 123 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 127 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 131 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 135 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 139 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 143 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 147 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 151 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 155 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 159 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 163 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 167 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 171 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 175 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 179 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 183 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 187 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 191 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 195 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 199 tmp/$1 experimenten/params_$1.txt
