/c/Users/Maarten/Miniconda3/python search.py 102 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 106 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 110 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 114 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 118 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 122 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 126 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 130 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 134 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 138 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 142 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 146 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 150 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 154 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 158 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 162 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 166 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 170 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 174 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 178 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 182 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 186 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 190 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 194 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 198 tmp/$1 experimenten/params_$1.txt
