/c/Users/vdmeulem/Miniconda3/python -O search.py 149 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 153 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 157 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 161 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 165 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 169 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 173 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 177 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 181 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 185 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 189 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 193 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 197 tmp/$1 experimenten/params_$1.txt
