python -O search.py 112  experimenten/params_$1.txt
python -O search.py 116  experimenten/params_$1.txt
python -O search.py 120  experimenten/params_$1.txt
python -O search.py 124  experimenten/params_$1.txt
python -O search.py 128  experimenten/params_$1.txt
python -O search.py 132  experimenten/params_$1.txt
python -O search.py 136  experimenten/params_$1.txt
python -O search.py 140  experimenten/params_$1.txt
python -O search.py 144  experimenten/params_$1.txt
