/c/Users/Maarten/Miniconda3/python -O search.py 115 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 119 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 123 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 127 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 131 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 135 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 139 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 143 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 147 experimenten/params_$1.txt
