/c/Users/Maarten/Miniconda3/python -O search.py 115 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 119 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 123 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 127 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 131 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 135 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 139 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 143 tmp/$1 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 147 tmp/$1 experimenten/params_$1.txt
