/c/Users/Maarten/Miniconda3/python -O search.py 148  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 152  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 156  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 160  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 164  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 168  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 172  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 176  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 180  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 184  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 188  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 192  experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 196  experimenten/params_$1.txt
