/c/Users/vdmeulem/Miniconda3/python -O search.py 148 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 152 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 156 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 160 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 164 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 168 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 172 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 176 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 180 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 184 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 188 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 192 tmp/$1  experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 196 tmp/$1  experimenten/params_$1.txt
