/c/Users/vdmeulem/Miniconda3/python -O search.py 114 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 118 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 122 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 126 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 130 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 134 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 138 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 142 tmp/$1 experimenten/params_$1.txt
/c/Users/vdmeulem/Miniconda3/python -O search.py 146 tmp/$1 experimenten/params_$1.txt
