/c/Users/Maarten/Miniconda3/python -O search.py 150 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 154 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 158 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 162 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 166 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 170 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 174 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 178 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 182 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 186 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 190 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 194 experimenten/params_$1.txt
/c/Users/Maarten/Miniconda3/python -O search.py 198 experimenten/params_$1.txt
