python -O search.py 113 experimenten/params_$1.txt
python -O search.py 117 experimenten/params_$1.txt
python -O search.py 121 experimenten/params_$1.txt
python -O search.py 125 experimenten/params_$1.txt
python -O search.py 129 experimenten/params_$1.txt
python -O search.py 133 experimenten/params_$1.txt
python -O search.py 137 experimenten/params_$1.txt
python -O search.py 141 experimenten/params_$1.txt
python -O search.py 145 experimenten/params_$1.txt
